### ISSUE TITLE
0.1 - Add sidebar that displays file metadata on single click

### ISSUE THREAD

**Issue by gmaddex** [cnap-cobre/synapse#41]
Users should be able to view arbitrary metadata about a file upon clicking it. This should be displayed in a slide out tray to the right of the file browser.

**Comment by kevindice** [comment]
Note, we're limiting this to just file metadata for now.  Agave-provided administrative metadata (who created it, why, what it represents, etc.) will come later.  File metadata is stuff that is already available such as creation time, last modified time, owner, file size, etc.

**Comment by kevindice** [comment]
Since you're going to be using the onClick action for this, we'll need to call `this.props.onSelectFile` for a double click instead.  This is in `FileList.js`.

**Comment by kevindice** [comment]
Done
