### ISSUE TITLE
4.5 - Prevent FileActionMenu from being cut off by bottom of file browser window on mobile

### ISSUE THREAD

**Issue by gmaddex** [cnap-cobre/synapse#47]
At the moment the file browser window cuts off any options that extend below the boundaries of the window, making actions inaccessible. This can possibly be fixed by adjusting the z-index on the FileActionMenu or by toggling the menu to drop up instead of down if it's one of the last elements of the table.

**Comment by kevindice** [comment]
No longer relevant because we're using right-click context menus now.
